FIX: inputMapStyle Kepler to load the defaultMapBoxStyleUrl
datatlas-erasme/front pull request #122
Opened 2022-08-17 10:23 UTC by OlivPi

2022-08-17 10:26 UTC, lutangar requested changes

2022-08-17 10:26 UTC, lutangar commented on src/components/map/Map.js
> -              appName="Datatlas"
Should be left intact or be configured via instance configuration.

2022-08-17 11:16 UTC, lutangar commented
@OlivPi could you rebase on `dev` please?

2022-08-19 13:54 UTC, lutangar commented on src/styles/styled.d.ts
> +    // Header: {
You probably should remove this commented code.

2022-08-19 14:15 UTC, OlivPi reviewed
I did a little cleaning (props and comment) on button's components and modal.

There is one comment left on ButtonSwitch style... Because i'm waiting some instruction about its design.

Sorry for the multi commits on the same review.

2022-08-24 12:05 UTC, lutangar approved these changes

2022-08-24 14:15 UTC, lutangar commented
Superseded by #133

2022-08-24 14:15 UTC, closed without merging