Dev industries
datatlas-erasme/front pull request #125
Opened 2022-08-18 10:59 UTC by Pipazoul

Rebased dev-industries on dev

2022-08-19 13:56 UTC, lutangar requested changes

2022-08-19 13:56 UTC, lutangar commented on README.md
> -# Front Setup
This `=` sign is probably a typo.

2022-08-19 13:56 UTC, lutangar commented on src/hooks/useInstanceConfiguration.ts
> +// Order an array with objects based on an string in order array
From our previous discussion, I suppose this ordering function is not used and afterall and could be removed.

2022-08-24 09:30 UTC, lutangar approved these changes

2022-08-24 09:47 UTC, OlivPi approved these changes

2022-08-24 12:00 UTC, lutangar commented on src/components/buttons/button-type/button-default/ButtonDefault.tsx
> +import { faTimes } from '@fortawesome/free-solid-svg-icons';
Nice catch !

2022-08-24 12:09 UTC, merged